resource_group_name         = "terraform_rg"
resource_group_location     = "East US"
virtual_network_name        = "vnet-tf"
subnet_name                 = "subnet-tf"
public_ip_name              = "publicip-tf"
network_security_group_name = "nsg-tf"
network_interface_name      = "nic-tf"
linux_virtual_machine_name  = "linuxvm-tf"
